name: portfolio
description: "Portfolio de Pierre"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
        sdk: flutter
  cupertino_icons: ^1.0.8

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  firebase_core: ^4.2.0
  firebase_remote_config: ^6.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  go_router: ^17.0.1
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/
    - assets/animations/
    - assets/fonts/
